spring.application.name=SGTPRO
spring.datasource.url=jdbc:mysql://localhost:3306/sgtpro
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.hibernate.SQL=debug

spring.thymeleaf.cache=false
