# Perfil de desarrollo
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
logging.level.com.example.sgtpro=debug
cors.allowed-origins=http://localhost:3000,http://localhost:4200,http://127.0.0.1:5500